Comment.create!([
  {user_id: 2, track_id: 8, body: "I love this song!"},
  {user_id: 2, track_id: 7, body: "Pretty good!"},
  {user_id: 2, track_id: 8, body: "ὠ0 ὠ0 ὠ0 ὠ0"},
  {user_id: 4, track_id: 3, body: "Goes great with the weather"},
  {user_id: 6, track_id: 2, body: "This seems like a rainy song!"},
  {user_id: 2, track_id: 9, body: "This seems like a rainy song!"},
  {user_id: 3, track_id: 2, body: "ὠ0 ὠ0 ὠ0 ὠ0"},
  {user_id: 1, track_id: 5, body: "I love this song!"},
  {user_id: 3, track_id: 5, body: "This seems like a rainy song!"},
  {user_id: 2, track_id: 8, body: "I love this song!"},
  {user_id: 1, track_id: 7, body: "Pretty good!"},
  {user_id: 1, track_id: 1, body: "ὠ0 ὠ0 ὠ0 ὠ0"},
  {user_id: 6, track_id: 3, body: "This seems like a rainy song!"},
  {user_id: 4, track_id: 6, body: "Goes great with the weather"},
  {user_id: 1, track_id: 9, body: "This seems like a rainy song!"},
  {user_id: 4, track_id: 3, body: "I love this song!"},
  {user_id: 5, track_id: 2, body: "Pretty good!"},
  {user_id: 5, track_id: 3, body: "ὠ0 ὠ0 ὠ0 ὠ0"},
  {user_id: 4, track_id: 9, body: "I love this song!"},
  {user_id: 5, track_id: 2, body: "I love this song!"},
  {user_id: 2, track_id: 1, body: "This seems like a rainy song!"},
  {user_id: 5, track_id: 5, body: "ὠ0 ὠ0 ὠ0 ὠ0"},
  {user_id: 6, track_id: 9, body: "ὠ0 ὠ0 ὠ0 ὠ0"},
  {user_id: 4, track_id: 9, body: "Pretty good!"},
  {user_id: 4, track_id: 8, body: "ὠ0 ὠ0 ὠ0 ὠ0"}
])
Track.create!([
  {title: "The Fragrance of Dark Coffee", description: "Rainy Chill Song.", user_id: 11, weather_id: 2, audio_url: "https://res.cloudinary.com/cloud-sounds/video/upload/v1472701577/xbfceaisgqo8vfghbed1.mp3", image_url: "https://res.cloudinary.com/cloud-sounds/image/upload/v1472701594/y9yvtgbdffdei0zhs6ii.jpg"},
  {title: "Hollaback Girl", description: "Whack", user_id: 11, weather_id: 1, audio_url: "https://res.cloudinary.com/cloud-sounds/video/upload/v1472702524/dkgaolkwxlirwwmumsxo.mp3", image_url: "https://res.cloudinary.com/cloud-sounds/image/upload/v1472702572/l10eiyjksbnln6abhisw.jpg"},
  {title: "Smooth", description: "Rockin 2000's jam", user_id: 11, weather_id: 3, audio_url: "https://res.cloudinary.com/cloud-sounds/video/upload/v1472757153/x8cvd8fkw2xnixp80edb.mp3", image_url: "https://res.cloudinary.com/cloud-sounds/image/upload/v1472757187/snjje2yunc2mlfaghcm4.jpg"},
  {title: "Drops of Jupiter", description: "Mellow Train song", user_id: 11, weather_id: 2, audio_url: "https://res.cloudinary.com/cloud-sounds/video/upload/v1472771679/cyuluso8tt3x4vdkoqob.mp3", image_url: "https://res.cloudinary.com/cloud-sounds/image/upload/v1472771717/hlaxnayutho348k0zelt.jpg"},
  {title: "Tik Tok", description: "Kesha always strikes twice", user_id: 11, weather_id: 5, audio_url: "https://res.cloudinary.com/cloud-sounds/video/upload/v1472773106/zjf3opgkz9p2hxxgcn8m.mp3", image_url: "http://res.cloudinary.com/cloud-sounds/image/upload/v1472772526/album_qfitcx.jpg"},
  {title: "You're Beautiful", description: "James Blunt fogged up the charts with this mellow hit", user_id: 11, weather_id: 4, audio_url: "https://res.cloudinary.com/cloud-sounds/video/upload/v1472773187/ktx6eh88t0acqka9pjrz.mp3", image_url: "https://res.cloudinary.com/cloud-sounds/image/upload/v1472773307/ds0re4upzs23e9roldui.jpg"},
  {title: "Party Rock Anthem", description: "The sunniest", user_id: 11, weather_id: 1, audio_url: "https://res.cloudinary.com/cloud-sounds/video/upload/v1472773451/mco3zj6rdwamuvyhvsmo.mp3", image_url: "https://res.cloudinary.com/cloud-sounds/image/upload/v1472773502/ktrh5usa3ny1l06wmwhj.jpg"},
  {title: "Breathe", description: "", user_id: 11, weather_id: 3, audio_url: "https://res.cloudinary.com/cloud-sounds/video/upload/v1472773652/xvnqy9vihtemr9io9lav.mp3", image_url: "https://res.cloudinary.com/cloud-sounds/image/upload/v1472773716/byfsomhufqemwzv44ean.jpg"}
])
User.create!([
  {username: "chauncey.ryan", email: "adah@rathdare.net", avatar_url: "http://res.cloudinary.com/cloud-sounds/image/upload/v1472868648/autoccaecatibeatae_s1rpz7.png", password_digest: "$2a$10$vpStuqvsOMMO9aoLFhrfgeG8QaI4MiuG/ahr/m9u8SVQAnEdRA2Oi", session_token: "NwjfTSTP1LO9RxQIoLm5yA"},
  {username: "arvid", email: "lela_johnson@steuber.info", avatar_url: "http://res.cloudinary.com/cloud-sounds/image/upload/v1472868648/autoccaecatibeatae_s1rpz7.png", password_digest: "$2a$10$NtzZ3B0Q2/nPfM6T8AZ19ebQeN0SBrRn.kk6gtp.kZp/lQzBigqvy", session_token: "1ieyzVDX8c0VO5v-IpP8JA"},
  {username: "isac", email: "ardith_erdman@boehm.co", avatar_url: "http://res.cloudinary.com/cloud-sounds/image/upload/v1472868645/molestiaererumvelit_1_jsb13k.png", password_digest: "$2a$10$tbjLKNpVjBnhHvHY3gmoS.itg.BstiHriR/zzBs0FmWgTxnJGGX9m", session_token: "QTVXPzZ_RNa5MXrJj7dpxw"},
  {username: "haie.sporer", email: "oswaldo_boyle@kerluke.co", avatar_url: "http://res.cloudinary.com/cloud-sounds/image/upload/v1472868636/etplaceatunde_tasf7c.png", password_digest: "$2a$10$nx3aNWwbpikcnrgbt6uM1.GUpJ1c9Gs.anP.7E/VtWtY/Xz72hYO.", session_token: "jy0DICL8zHGwUFhtccbJIQ"},
  {username: "angel.kilback", email: "augustine.donnelly@bashirian.net", avatar_url: "http://res.cloudinary.com/cloud-sounds/image/upload/v1472868652/recusandaeeaet_ig3wz9.png", password_digest: "$2a$10$sX7DSNXMUd8Xn/FTyng30uMBxx.JIJWoXRypR6qve26zlz9XSapSO", session_token: "b9DZ7zxHY4Zg8S_1DpR3BQ"},
  {username: "mac.ritchie", email: "treva@hammes.info", avatar_url: "http://res.cloudinary.com/cloud-sounds/image/upload/v1472868652/recusandaeeaet_ig3wz9.png", password_digest: "$2a$10$6k8XeK.IFg/OXdjYnrXNv./Nk5MPghPpRoRbupGU6hL9XwN2L2jQq", session_token: "BhATkXt-MRbwq33UZFZSMg"},
  {username: "orin", email: "veronica.casper@schuppe.name", avatar_url: "http://res.cloudinary.com/cloud-sounds/image/upload/v1472868636/etplaceatunde_tasf7c.png", password_digest: "$2a$10$qBVMady8MWfauMT8taDfIOYNszrrmahqvkvfh//1Fd6YXIzzmv2fe", session_token: "Il5rQCIvbsUinwIf53yc1Q"},
  {username: "fernando", email: "edmund.hyatt@hilpert.biz", avatar_url: "http://res.cloudinary.com/cloud-sounds/image/upload/v1472868648/autoccaecatibeatae_s1rpz7.png", password_digest: "$2a$10$93z2Dmc8VH5Qn37o0/g.8OyLLyiOo1sO8HrsRjRVRuQ7qE579hhAy", session_token: "9_nOUcvDHRntT43JSqz5bw"},
  {username: "velva", email: "kayleigh@parkerdurgan.biz", avatar_url: "http://res.cloudinary.com/cloud-sounds/image/upload/v1472868652/recusandaeeaet_ig3wz9.png", password_digest: "$2a$10$leSwN0nPAu5rMqUvdiJsSOBHpeccxJLFVbc.4zCh0pgvk4fqTY9ZW", session_token: "qIl9e2_eLFW8Qu-kjPudrg"},
  {username: "aurelio_funk", email: "arturo.monahan@mohr.net", avatar_url: "http://res.cloudinary.com/cloud-sounds/image/upload/v1472868636/etplaceatunde_tasf7c.png", password_digest: "$2a$10$Z9tZjQH9Pxtd13Q8bvtnIuv8KYUcEc0.nLuWtTIQK1PtXDWsQtlQa", session_token: "n57oTewj7r30p7xrbFz8CA"},
  {username: "Guest", email: "audra@mckenzie.name", avatar_url: "http://res.cloudinary.com/cloud-sounds/image/upload/v1472868648/autoccaecatibeatae_s1rpz7.png", password_digest: "$2a$10$oZiIww3YW6WKfeVJrZXtbu6TG.01G/HG/otz2gypZ2mdK6JPfy4j.", session_token: "87vpFWteuDvLag5SHbyToQ"}
])
